application: event-reporter
version: prod
runtime: go
api_version: go1

handlers:
- url: /backend/.*
  secure: always
  script: _go_app
- url: /frontend/.*
  secure: always
  script: _go_app
- url: /static
  secure: always
  static_dir: static